---
  - name: Ensure ca-certificates is installed
    apt:
      name: ca-certificates
      state: present
      update_cache: yes

  - name: Download the NodeSource GPG key
    shell: |
      curl -o /tmp/nodesource.gpg.key https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    args:
      warn: false

  - name: Add the NodeSource GPG key
    apt_key:
      file: "/tmp/nodesource.gpg.key"
      state: present

  - name: Install the Node.js LTS repository
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes

  - name: Install Node.js
    apt:
      name: 
        - nodejs
        - npm
      state: present