apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
     {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  db_host: {{ .Values.mysql.host | b64enc | quote }}
  db_port: {{ .Values.mysql.port | b64enc | quote }}
  db_user: {{ .Values.mysql.user | b64enc | quote }}
  db_password: {{ .Values.mysql.password | b64enc | quote }}