pipeline {
    agent any
    environment {
        registry = 'docker.io'  
        registryCredential = 'docker' 
    }
 
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/santoshPagire/ecommerce_web.git', branch: 'main'
            }
        }

        stage('build and push image ') {
            steps{
                script{
                    docker.withRegistry('', registryCredential){
                        def customImage = docker.build("santoshpagire/ecommerce-app")
                        customImage.push()
                        

                    }
                    
                }
            }
        }
        
    }
 
  
}
