---
- name: Configure service
  hosts: target
  become: yes  
  tasks:
    - name: Install nginx 
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure nginx with parameters
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf

